### ISSUE TITLE
Keep getting "This app requires Wifi or Mobile data access to be enabled"

### ISSUE THREAD

**Issue by JohnCKeogh** [bluecats/bluecats-scratchingpost-android#7]
Hi

I have downloaded this code and changed the app key to the one generated by the Bluecats system when I created a new Android app. The project builds fine but when I run it on a Samsung S6 (Marshmallow) or Nexus 7 (Lollipop) I just get the message "This app requires Wifi or Mobile data access to be enabled". However I have these enabled on both these devices as well as Bluetooth and Location Services. Any help would be appreciated.

Thanks

**Comment by theporkchopexpress** [comment]
I am marking this issue to be closed. Please comment if you require further support.

Cheers,
